[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.93"
tokio = "1.25.0"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
