ServerPort = 3001
ServerUrl = "http://localhost:3001/"
NativeProofGenerationEnabled = true
PublishingKeyPath = "pbkey"
OnChainCheckStatusFrecuency = "30s"

[Database]
Url="postgres://polygonid:polygonid@localhost:5431/platformid?sslmode=disable"

[Cache]
RedisUrl="redis://@localhost:6379/1"

[HTTPBasicAuth]
User = "user"
Password = "password"

[Log]
Level = -4
Mode = 2

[KeyStore]
Address="http://localhost:8200/"
Token="hvs.ESjjYOSVBZq9FsUIkBMOfBjD"
PluginIden3MountPath="iden3"

[ReverseHashService]
URL="http://localhost:3001/"
Enabled= false

[Ethereum]
URL="https://polygon-mumbai.infura.io/v3/86bd59eec9644914a8dc6dedc9f08487"
ContractAddress="0x134B1BE34911E39A8397ec6289782989729807a4"
DefaultGasLimit=600000
ConfirmationTimeout="600s"
ConfirmationBlockCount=5
ReceiptTimeout="600s"
MinGasPrice=0
MaxGasPrice=1000000
RPCResponseTimeout="5s"
WaitReceiptCycleTime="30s"
WaitBlockCycleTime="30s"

[Prover]
ServerURL="http://localhost:8002/"
ResponseTimeout="600s"

[Circuit]
Path="./pkg/credentials/circuits"